### ISSUE TITLE
Version does not seem updated.

### ISSUE THREAD

**Issue by custa1200** [proteanstudio/sketch-palette-cleanser#21]
Every time I try to install the later plugins 1.4.3 etc, Sketch tells me that 1.04 is already installed do you want to reinstall it. Something is messed with the versionsing. when trying to automatically update through the Sketch app it installs nothing new there either and just continually says an update is available.

**Comment by rodnem** [comment]
Same here

**Comment by abdulmhamid** [comment]
@custa1200 Thanks for opening this issue and PR.  We will take a look shortly to clear the error.

**Comment by abdulmhamid** [comment]
We have published a `v1.4.4` patch to address this issue. Thanks again.
