### ISSUE TITLE
Groups sizes are not define by the content dimensions

### ISSUE THREAD

**Issue by rodnem** [proteanstudio/sketch-palette-cleanser#22]
It's annoying because you can't select shapes with breaking all groups.
A workaround is to shift+drag a selection around them to select individually each object… then the groups sizes are redifined.

**Comment by abdulmhamid** [comment]
@rodnem Thanks for opening an issue. 

Can you please clarify what you are asking for here? The generated artboard is for informational purposes only. What resizing or reordering behavior are you trying to accomplish?

Visual aids would be helpful.
